### PR TITLE
Replace the HelloWorld example project with the TallestTowers example project

### PR DESCRIPTION
**Pull request by daveverwer**
Note: This PR also includes the initial commits to HelloWorld project for Xcode 11, just in case anyone ever wants to go back to that.

### CODE REVIEW

**Comment by markoa** [comment]
@daveverwer I was looking through the build logs and realized that it would be good to demonstrate use of [artifacts](https://docs.semaphoreci.com/article/155-artifacts), a feature we recently added to Semaphore.

I wanted to add a line like `artifact push workflow build/app.ipa` at the end of the Build block, but it looks like we don't generate such a file here? If so could you extend the configuration so that it creates an app file?

Thanks!

**Comment by daveverwer** [comment]
Sure thing, I'll get to this as soon as I can.

**Comment by daveverwer** [comment]
Hi Marko, and apologies for the delay. I've had a go at this today.

As you say, it would be great if we could have the example project upload an IPA file as an artefact but that's a bit tricky in a clone-able project like this. In order to export an IPA code signing needs to be fully configured, which will make it hard for us to create a project that potential customers can quickly clone and test. Currently it's a case of forking the example project and adding the clone to Semaphore, and we don't want that to become too much of a chore.

So, I thought maybe we could export a simulator IPA archive. It's easy to get a .xcarchive produced of a simulator build, but Xcode *really* doesn't want to export that as an IPA without signing it. I'm not particularly surprised, because even though it'd be good for our needs here it's not really a thing people would want to do in the real world.

However, if demonstrating artefacts is the goal then maybe we could choose something else to keep things a little simpler in the example project?

I've made a branch of this repository with an additional Semaphore block with a fastlane automation that creates two screenshots, on two different device sizes that could be uploaded as App Store metadata.

So, firstly is this a good compromise that demonstrates what you need?

Second, I don't think artefacts are working for me on that build server. I tried:

`artifact push project screenshots`

Where screenshots is a folder in the project root, but it failed with this error:

```
artifact push project screenshots
bash: artifact: command not found
exit code: 1 duration: 0s
```

The `semaphore.yml` is [here](https://github.com/daveverwer/semaphore-demo-ios-swift-xcode/blob/screenshots/.semaphore/semaphore.yml):

**Comment by markoa** [comment]
AFAIK our [Fastlane plugin](https://github.com/semaphoreci/fastlane-plugin-semaphore) is supposed to make code signing "just work" for testing purposes, by generating a temporary keychain. I didn't realize originally but it looks like your project is not using it. If that's the case, please go ahead and try it. :)

I'll get back to you re. why artifact command failed.

**Comment by markoa** [comment]
Team fixed the `artifact: command not found` error, should not be happening any more.

**Comment by daveverwer** [comment]
This project now supports storing an IPA file and also sample App Store screenshots as job artifacts when the build runs on CI. There are also full instructions for whoever clones the repository on how to set themselves up with fastlane match.

**Comment by markoa** [comment]
👏 👏 👏

**Comment by daveverwer** [comment]
👍

**Pull request merged**
